### ISSUE TITLE
error in mbpls with blockscale="none"

### ISSUE THREAD

**Issue by flomehl** [khliland/multiblock#1]
Hello, 

I think there is a small error in the code for mbpls: when using blockscale "none" Xc is defined at line 132 but used at line 124.
thanks for the very nice package though,

best

Florence

**Comment by khliland** [comment]
Dear Florence,

Thank you for letting me know about this error. I have now corrected it in my local code and will push it to GitHub soon.

Best regards,
Kristian

**Comment by khliland** [comment]
Bugfix Pushed. CRAN submission on its way.

Kristian

**Comment by flomehl** [comment]
great! so efficient! thanks
