### ISSUE TITLE
SO-PLS Cross-Validation results are different from standard PLS

### ISSUE THREAD

**Issue by ldan29** [khliland/multiblock#3]
Hi,

I may have found an issue with the results returned by the SOPLS function, specifically the RMSECV. Obviously I am looking at the case where only 1 of my blocks would be usefull (optimal model uses 0 factors for all the other blocks).

If I create a standard PLS model (with the package "PLS") using this block, using the same CV parameters and looking at the same number of PLS factors, the RMSECV are slightly different. The Y explained variance is the same however which is logical.

Is this behavior expected ? This is my first time time submitting an issue so I hope my explanations are clear. I can provide an exemple with code if necessary.

**Comment by khliland** [comment]
Hi Idan29,

Could you test the version of multiblock uploaded today on GitHub using the devools-install? The update is specifically aimed at this issue.

Regards,
Kristian

**Comment by ldan29** [comment]
Hi,

It appears to be fixed ! I have tested with a cross validation using interleaved segments, which is not the default behavior, and it gives exactly the same results. Thank you very much for your reactivity :)
